"""AsyncAPI 2.6 / 3.0 Specification Generator for IoT & Event-Driven APIs.

Synthesizes standard AsyncAPI 3.0 specs from static code discovery of MQTT topics,
CoAP endpoints, and WebSocket channels.
"""
import json
from typing import Dict, List, Any


class AsyncAPIGenerator:
    def __init__(self, title: str = "MazAPI IoT AsyncAPI Spec", version: str = "1.0.0"):
        self.title = title
        self.version = version

    def generate_spec(self, endpoints: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generates AsyncAPI 3.0 specification dictionary from parsed IoT endpoints."""
        asyncapi_doc = {
            "asyncapi": "3.0.0",
            "info": {
                "title": self.title,
                "version": self.version,
                "description": "Synthesized AsyncAPI Specification generated by MazAPI IoT App Surface Engine."
            },
            "servers": {
                "mqtt_broker": {
                    "host": "localhost:1883",
                    "protocol": "mqtt",
                    "description": "Default Enterprise / Edge MQTT Broker"
                },
                "coap_server": {
                    "host": "localhost:5683",
                    "protocol": "coap",
                    "description": "Constrained Application Protocol (CoAP) Endpoint"
                }
            },
            "channels": {},
            "operations": {},
            "components": {
                "messages": {}
            }
        }

        for idx, ep in enumerate(endpoints):
            path = ep.get("path", "/telemetry")
            protocol = ep.get("protocol", "MQTT").lower()
            method = ep.get("method", "SUBSCRIBE").lower()
            framework = ep.get("framework", "IoT Channel")

            # Clean channel key for AsyncAPI
            channel_key = path.replace("/", "_").replace("+", "single").replace("#", "wildcard").strip("_")
            if not channel_key:
                channel_key = f"channel_{idx}"

            asyncapi_doc["channels"][channel_key] = {
                "address": path,
                "messages": {
                    f"{channel_key}_msg": {
                        "$ref": f"#/components/messages/{channel_key}_msg"
                    }
                },
                "description": f"IoT Messaging Channel discovered from {framework}"
            }

            op_key = f"{method}_{channel_key}"
            asyncapi_doc["operations"][op_key] = {
                "action": "receive" if method in ("subscribe", "get") else "send",
                "channel": {
                    "$ref": f"#/channels/{channel_key}"
                },
                "summary": f"Operation on {path} via {protocol.upper()}",
                "security": [] if not ep.get("has_auth") else [{"mqttAuth": []}]
            }

            asyncapi_doc["components"]["messages"][f"{channel_key}_msg"] = {
                "name": f"{channel_key}Message",
                "title": f"Payload for {path}",
                "summary": f"Schema for {protocol.upper()} payload on {path}",
                "contentType": "application/json",
                "payload": {
                    "type": "object",
                    "properties": {
                        "device_id": {"type": "string", "example": "sensor_node_01"},
                        "timestamp": {"type": "integer", "example": 1724483166},
                        "telemetry": {"type": "object"}
                    }
                }
            }

        return asyncapi_doc

    def export_json(self, endpoints: List[Dict[str, Any]], output_path: str) -> None:
        spec = self.generate_spec(endpoints)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(spec, f, indent=2)
